/* eslint-disable */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'gb',
    path: '/gb',
    component: 'layout.base',
    meta: {
      title: '国标管理',
      icon: 'icon-park:devices',
    },
    children: [
      {
        name: 'gb_device',
        path: '/gb/device',
        component: 'view.gb_device',
        meta: {
          title: '国标管理',
          icon: 'icon-park:surveillance-cameras',
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页',
      icon: 'icon-park:home-two',
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'live',
    path: '/live',
    component: 'layout.base',
    meta: {
      title: '视频广场',
      icon: 'icon-park:video-conference',
    },
    children: [
      {
        name: 'live_video',
        path: '/live/video',
        component: 'view.live_video',
        meta: {
          title: '分屏管理',
          icon: 'icon-park:data-screen',
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'media',
    path: '/media',
    component: 'layout.base',
    meta: {
      title: '流媒体管理',
      icon: 'icon-park:surveillance-cameras-one',
    },
    children: [
      {
        name: 'media_pull-stream',
        path: '/media/pull-stream',
        component: 'view.media_pull-stream',
        meta: {
          title: '拉流代理',
          icon: 'icon-park:pull-requests',
        }
      },
      {
        name: 'media_push-stream',
        path: '/media/push-stream',
        component: 'view.media_push-stream',
        meta: {
          title: '推流管理',
          icon: 'icon-park:invert-camera',
        }
      }
    ]
  },
  {
    name: 'node',
    path: '/node',
    component: 'layout.base',
    meta: {
      title: '节点管理',
      icon: 'icon-park:triangle-round-rectangle',
    },
    children: [
      {
        name: 'node_zlm',
        path: '/node/zlm',
        component: 'view.node_zlm',
        meta: {
          title: 'ZLM管理',
          localIcon: 'zlm',
        }
      }
    ]
  },
  {
    name: 'onvif',
    path: '/onvif',
    component: 'layout.base',
    meta: {
      title: 'ONVIF管理',
      icon: 'icon-park:online-meeting',
    },
    children: [
      {
        name: 'onvif_device',
        path: '/onvif/device',
        component: 'view.onvif_device',
        meta: {
          title: 'ONVIF设备',
          icon: 'icon-park:network-tree',
        }
      }
    ]
  },
  {
    name: 'record',
    path: '/record',
    component: 'layout.base',
    meta: {
      title: '录像回放',
      icon: 'icon-park:record-player',
    },
    children: [
      {
        name: 'record_video',
        path: '/record/video',
        component: 'view.record_video',
        meta: {
          title: '录像回放',
          icon: 'icon-park:videocamera-one',
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: '系统设置',
      icon: 'icon-park:system',
    },
    children: [
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: '用户管理',
          icon: 'icon-park:user',
        }
      }
    ]
  }
];
